const { chromium } = require('playwright');
const assert=require('node:assert/strict');const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://localhost:3000',{waitUntil:'networkidle'});await page.screenshot({path:'test-results/welcome-mobile.png',fullPage:true});await page.click('#begin');assert.equal(await page.locator('#bpm').innerText(),'--');await page.click('#demoHome');await page.waitForFunction(()=>document.querySelector('#bpm').textContent!=='--');await page.screenshot({path:'test-results/dashboard-mobile.png',fullPage:true});await page.click('.bottom-nav [data-page=trends]');await page.click('[data-chart=accel]');assert.match(await page.locator('#chartTitle').innerText(),/Gia tốc/);const downloadPromise=page.waitForEvent('download');await page.locator('.session-card .export-action').click();const download=await downloadPromise;await download.saveAs('test-results/demo.csv');assert.match(fs.readFileSync('test-results/demo.csv','utf8'),/SIMULATED/);await page.click('#stopDemo');await page.click('.bottom-nav [data-page=home]');assert.equal(await page.locator('#bpm').innerText(),'--');await page.click('.bottom-nav [data-page=settings]');await page.click('#install');assert.equal(await page.locator('dialog').isVisible(),true);await page.locator('dialog .button.dialog-close').click();await page.click('#clearData');await page.click('#confirmClear');assert.equal(await page.locator('#recordCount').innerText(),'0');
for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});await page.goto('http://localhost:3000/#home');const dims=await page.evaluate(()=>({sw:document.documentElement.scrollWidth,w:innerWidth}));assert.equal(dims.sw<=dims.w,true,`Overflow at ${width}: ${JSON.stringify(dims)}`);}
await page.click('#demoHome');await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});await page.click('#stopDemo');
// Exercise the actual Bluetooth connection path with a browser-side GATT transport double.
await page.evaluate(()=>{const chars={};for(let i=1;i<=3;i++){const c=new EventTarget();c.startNotifications=async()=>c;c.readValue=async()=>{const s=i===1?'78':i===2?'0.12,-0.35,9.76':'85432';return new DataView(new TextEncoder().encode(s).buffer)};chars['37af000'+i+'-39a2-4fce-9c60-01ee00000000']=c;}const device=new EventTarget();device.name='VieGrand-Sensor';device.gatt={connected:false,connect:async()=>{device.gatt.connected=true;return{getPrimaryService:async uuid=>{if(uuid!=='37af0000-39a2-4fce-9c60-01ee00000000')throw Error('UUID mismatch');return{getCharacteristic:async id=>chars[id]}}}},disconnect:()=>{device.gatt.connected=false;device.dispatchEvent(new Event('gattserverdisconnected'));}};Object.defineProperty(navigator,'bluetooth',{configurable:true,value:{requestDevice:async options=>{window.__requestOptions=options;return device}}});window.__ble={device,chars};});
await page.click('#connectHome');await page.waitForFunction(()=>document.querySelector('#statusBadge').textContent.includes('Đã kết nối'));assert.equal(await page.locator('#bpm').innerText(),'78');assert.equal(await page.locator('#ax').innerText(),'0.12');assert.equal(await page.locator('#az').innerText(),'9.76');assert.equal(await page.locator('#ir').innerText(),'85.432');await page.evaluate(()=>{const c=window.__ble.chars['37af0001-39a2-4fce-9c60-01ee00000000'];c.value=new DataView(new TextEncoder().encode('-1').buffer);c.dispatchEvent(new Event('characteristicvaluechanged'));});assert.equal(await page.locator('#bpm').innerText(),'--');await page.evaluate(()=>{const c=window.__ble.chars['37af0002-39a2-4fce-9c60-01ee00000000'];c.value=new DataView(new TextEncoder().encode(',1,2').buffer);c.dispatchEvent(new Event('characteristicvaluechanged'));});assert.equal(await page.locator('#ax').innerText(),'0.12');await page.evaluate(()=>window.__ble.device.gatt.disconnect());assert.equal(await page.locator('#statusBadge').innerText(),'Chưa kết nối');assert.equal(await page.locator('#magnitude').innerText(),'--');
await page.click('#connectHome');await page.waitForFunction(()=>document.querySelector('#bpm').textContent==='78');await page.waitForTimeout(4000);assert.equal(await page.locator('#bpm').innerText(),'--');await page.click('#connectHome');
// A failed characteristic subscription must clean up the connection.
await page.evaluate(()=>{window.__ble.chars['37af0002-39a2-4fce-9c60-01ee00000000'].startNotifications=async()=>{throw new Error('Test subscription failure')}});await page.click('#connectHome');await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Test subscription failure'));assert.equal(await page.evaluate(()=>window.__ble.device.gatt.connected),false);
assert.equal(errors.length,0,errors.join('\n'));await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);await page.reload();assert.equal(await page.locator('#app').isVisible(),true);await context.setOffline(false);console.log('PASS: welcome, demo, navigation, CSV, clear, install help, widths 320/390/768/1440, BLE UUID/read/notify/invalid packets/-1/disconnect/stale/partial failure, offline PWA, no page errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
